version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    links:
      - mongo:27017
    environment:
      PORT: 5000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: "--smallfiles --logpath=/dev/null"