version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    links:
      - mongo
    environment:
      PORT: 5000
    command: nodemon index.js
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data:/data/db
